api/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += [
#         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     ]

main/urls.py
from django.urls import path
from . import views
from main.views import completed, renovation, projects, house_construction, extensions

app_name = "main"
urlpatterns = [
    path("", views.MainPageView.as_view(), name="form_view"),
    path("completed", completed, name="completed"),
    path("renovation", renovation, name="renovation"),
    path("projects", projects, name="projects"),
    path("house_construction", house_construction, name="house_construction"),
    path("extensions", extensions, name="extensions"),
]

main/models.py
from django.db import models
from django.utils import timezone


class Question(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.name}"

    def create(self):
        self.created_date = timezone.now()
        self.save()


class Image(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField(upload_to="", blank=True)
    file = models.FileField(upload_to="", blank=True)

    def __str__(self):
        return f"{self.title}"

main/forms.py
from django import forms
from . import models


class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [
            "name",
            "email",
            "text"
        ]
        labels = {
            "name": "",
            "email": "",
            "text": ""
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "fill__input", "placeholder": "NAMN"}),
            "email": forms.TextInput(attrs={"class": "fill__input", "placeholder": "EMAIL"}),
            "text": forms.TextInput(attrs={"class": "fill__text", "placeholder": "MEDDELANDE"}),
        }

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.urls import reverse
from django.views.generic import CreateView, ListView, TemplateView, View
from django.views.generic.edit import FormMixin
from . import models, forms
from main.models import Question
from main.forms import QuestionForm


class MainPageView(CreateView, ListView):
    template_name = "main/index.html"
    model = models.Question
    success_url = "/"
    form_class = QuestionForm

    def get_context_data(self, **kwargs):
        context = super(MainPageView, self).get_context_data(**kwargs)
        context['form'] = QuestionForm()
        return context

    def get_queryset(self):
        return models.Question.objects.all()

    def form_valid(self, form):
        return super().form_valid(form=form)


def completed(request):
    return render(request, "main/completed.html")


def renovation(request):
    return render(request, "main/renovation.html")


def projects(request):
    return render(request, "main/projects.html")


def house_construction(request):
    return render(request, "main/house_construction.html")


def extensions(request):
    return render(request, "main/extensions.html")

templates/main/awesome.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Awesome {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/libs/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/libs/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/fill.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/photo.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/pictures.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/gallery.css' %}">
</head>
<body>
    {% block content %}

<header class="header">
    <div class="container">
            <div class="header__logo">
                <img src="{% static 'main/images/Logo.png' %}" alt="logo">
                <h1 class="header__title"> SUAB Bygg och VVS</h1>
            </div>

        <div class="header__block">
            <h2 class="header__title2"> SUAB Bygg och VVS</h2>
            <p class="header__description">- ett företag som värnar om kunden och dennes intressen. Vårt mål är att alltid ha nöjda kunder,
                <br> nöjda kunder lika vanliga kunder.</p>

            <button class="header__button">Button</button>
        </div>
    </div>
</header>

<section class="main">
    <div class="container">
            <img class="main__img" src="{% static 'main/images/imageMain.png' %}" alt="">
            <h2 class="main__title">Om oss</h2>
            <p class="main__description"> SUAB Bygg och VVS — ett företag som värnar om kunden och dennes intressen. Vårt mål är att
                <br> alltid ha nöjda kunder, nöjda kunder lika vanliga kunder.</p>
            <p class="main__description2"> Vi bistår privatpersoner och företag i alla typer av byggentreprenader såsom tillbyggnad, fönsterförsäljning, badrumsrenovering, nybyggnation m.m.</p>

        <div class="main__row">
                <div class="main__block">
                    <div class="main__one">
                        <p class="main__descr">1</p>
                    </div>

                    <div class="main__text">
                        <h3 class="main__title2">TILLBYGGNADER</h3>
                        <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                    </div>
                </div>

               <div class="main__block">
                   <div class="main__one">
                       <p class="main__descr">1</p>
                   </div>

                   <div class="main__text">
                       <h3 class="main__title2">TILLBYGGNADER</h3>
                       <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                   </div>
               </div>

                    <div class="main__block">
                        <div class="main__one">
                            <p class="main__descr">1</p>
                        </div>

                        <div class="main__text">
                            <h3 class="main__title2">TILLBYGGNADER</h3>
                            <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                        </div>
                    </div>


                   <div class="main__block">
                       <div class="main__one">
                           <p class="main__descr">1</p>
                       </div>

                       <div class="main__text">
                           <h3 class="main__title2">TILLBYGGNADER</h3>
                           <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                       </div>
                   </div>
            </div>
    </div>
</section>

<section class="photo">
            <div class="container">
                            <img class="photo__img" src="{% static 'main/images/photo.png' %}" alt="photo">


                <div class="photo__row">
                    <div class="photo__contents">
                        <img class="photo__block" src="{% static 'main/images/photo1.png' %}" alt="">
                        <img class="photo__block" src="{% static 'main/images/photo2.png' %}" alt="">
                    </div>

                    <div class="photo__content">
                        <img class="photo__block" src="{% static 'main/images/photo5.png' %}" alt="">
                        <img class="photo__block" src="{% static 'main/images/photo6.png' %}" alt="">
                    </div>
                </div>

                <div class="photo__row1">
                    <div class="photo__contents">
                        <img class="photo__block" src="{% static 'main/images/photo3.png' %}" alt="">
                        <img class="photo__block" src="{% static 'main/images/photo4.png' %}" alt="">
                    </div>

                    <div class="photo__content">
                        <img class="photo__block" src="{% static 'main/images/photo5.png' %}" alt="">
                        <img class="photo__block" src="{% static 'main/images/photo5.png' %}" alt="">
                    </div>
                </div>
            </div>
        </section>

<section class="gallery">
    <div class="container">
        <h2 class="gallery__title">PÅGÅENDE PROJEKT</h2>

        <div class="gallery__block">
            <button class="gallery__btn">TOTALRENOVERING ATTEFALLSHUS</button>
            <button class="gallery__btn">TIDIGARE SLUTFÖRDA PROJEKT</button>
        </div>

        <div class="gallery__block">
            <button class="gallery__btn">HUSBYGGE - JÄRLÅSA</button>
            <button class="gallery__btn">TILLBYGGNADER & POOL</button>
        </div>

        <div class="owl-carousel owl-theme owl-loaded">
            <div class="owl-stage-outer ">
                <div class="owl-stage">
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="{% static 'main/images/gallery1.png' %}" id="1" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img active" src="{% static 'main/images/gallery2.png' %}" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="{% static 'main/images/gallery3.png' %}" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="{% static 'main/images/gallery4.png' %}" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="{% static 'main/images/gallery5.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="fill">
    <div class="container">
        <h2 class="fill__title">VILL DU ATT VI KONTAKTAR DIG? <br>
            FYLL I FORMULÄRET NEDAN SÅ HÖR VI AV OSS TILL DIG</h2>

        <form class="fill__form" action="" method="POST">
            {% csrf_token %}
            {{ form }}
            <input class="fill__btn" type="submit" value="SKICKA" />
        </form>

    </div>
</section>

<section class="footer">
    <div class="container">
        <img class="footer__image" src="{% static 'main/images/footer.png' %}" alt="">
       <div class="footer__info">
           <div class="footer__block">
               <h3 class="footer__title">Logotype</h3>
               <div class="footer__icons">
                   <img src="{% static 'main/images/icon1.png' %}" alt="facebook">
                   <img src="{% static 'main/images/icon2.png' %}" alt="instagram">
                   <img src="{% static 'main/images/icon3.png' %}" alt="telegram">
                   <img src="{% static 'main/images/icon4.png' %}" alt="whatsapp">
               </div>
               <p class="footer__descr">Lorem ipsum Lorem ipsum</p>
           </div>

           <div class="footer__contact">
               <h3 class="footer__title">Contact us</h3>
               <p class="footer__description">Phone number: +996 706 05 02 03</p>
               <p class="footer__description">Adress: Ibraimova street 103</p>
               <p class="footer__description3">E-mail: loremipsum@gmail.com</p>
           </div>
       </div>
    </div>
</section>



<script type="text/javascript" src="{% static 'main/js/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/libs/owl-carousel/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>

    {% endblock %}
</body>
</html>

templates/main/header_footer.html
{% extends 'main/origin.html' %}
{% load static %}

{% block title %}Awesome{% endblock %}

{% block content %}

<!--<h1>Beautiful form</h1>-->


<header class="header">
    <div class="container">
            <div class="header__logo">
                <img src="main/images/Logo.png" alt="">
                <h1 class="header__title"> SUAB Bygg och VVS</h1>
            </div>

        <div class="header__block">
            <h2 class="header__title2"> SUAB Bygg och VVS</h2>
            <p class="header__description">- ett företag som värnar om kunden och dennes intressen. Vårt mål är att alltid ha nöjda kunder,
                <br> nöjda kunder lika vanliga kunder.</p>

            <button class="header__button">Button</button>
        </div>
    </div>
</header>

<section class="main">
    <div class="container">
            <img class="main__img" src="{% static 'main/images/imageMain.png' %} alt="">
            <h2 class="main__title">Om oss</h2>
            <p class="main__description"> SUAB Bygg och VVS — ett företag som värnar om kunden och dennes intressen. Vårt mål är att
                <br> alltid ha nöjda kunder, nöjda kunder lika vanliga kunder.</p>
            <p class="main__description2"> Vi bistår privatpersoner och företag i alla typer av byggentreprenader såsom tillbyggnad, fönsterförsäljning, badrumsrenovering, nybyggnation m.m.</p>

        <div class="main__row">
                <div class="main__block">
                    <div class="main__one">
                        <p class="main__descr">1</p>
                    </div>

                    <div class="main__text">
                        <h3 class="main__title2">TILLBYGGNADER</h3>
                        <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                    </div>
                </div>

               <div class="main__block">
                   <div class="main__one">
                       <p class="main__descr">1</p>
                   </div>

                   <div class="main__text">
                       <h3 class="main__title2">TILLBYGGNADER</h3>
                       <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                   </div>
               </div>

                    <div class="main__block">
                        <div class="main__one">
                            <p class="main__descr">1</p>
                        </div>

                        <div class="main__text">
                            <h3 class="main__title2">TILLBYGGNADER</h3>
                            <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                        </div>
                    </div>


                   <div class="main__block">
                       <div class="main__one">
                           <p class="main__descr">1</p>
                       </div>

                       <div class="main__text">
                           <h3 class="main__title2">TILLBYGGNADER</h3>
                           <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                       </div>
                   </div>
            </div>
    </div>
</section>

<section class="photo">
            <div class="container">
                            <img class="photo__img" src="main/images/photo.png" alt="photo">


                <div class="photo__row">
                    <div class="photo__contents">
                        <img class="photo__block" src="main/images/photo1.png" alt="">
                        <img class="photo__block" src="main/images/photo2.png" alt="">
                    </div>

                    <div class="photo__content">
                        <img class="photo__block" src="main/images/photo5.png" alt="">
                        <img class="photo__block" src="main/images/photo6.png" alt="">
                    </div>
                </div>

                <div class="photo__row1">
                    <div class="photo__contents">
                        <img class="photo__block" src="main/images/photo3.png" alt="">
                        <img class="photo__block" src="main/images/photo4.png" alt="">
                    </div>

                    <div class="photo__content">
                        <img class="photo__block" src="main/images/photo5.png" alt="">
                        <img class="photo__block" src="main/images/photo5.png" alt="">
                    </div>
                </div>
            </div>
        </section>

<section class="gallery">
    <div class="container">
        <h2 class="gallery__title">PÅGÅENDE PROJEKT</h2>

        <div class="gallery__block">
            <button class="gallery__btn">TOTALRENOVERING ATTEFALLSHUS</button>
            <button class="gallery__btn">TIDIGARE SLUTFÖRDA PROJEKT</button>
        </div>

        <div class="gallery__block">
            <button class="gallery__btn">HUSBYGGE - JÄRLÅSA</button>
            <button class="gallery__btn">TILLBYGGNADER & POOL</button>
        </div>

        <div class="owl-carousel owl-theme owl-loaded">
            <div class="owl-stage-outer ">
                <div class="owl-stage">
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="main/images/gallery1.png" id="1" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img active" src="main/images/gallery2.png" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="main/images/gallery3.png" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="main/images/gallery4.png" alt="">
                    </div>
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="main/images/gallery5.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="fill">
    <div class="container">
        <h2 class="fill__title">VILL DU ATT VI KONTAKTAR DIG? <br>
            FYLL I FORMULÄRET NEDAN SÅ HÖR VI AV OSS TILL DIG</h2>






<div class="form">
  <form class="create" action="." method="POST">
    {% csrf_token %}
    {{ form }}
    <input class="addbtn" type="submit" value="Add" />
  </form>
</div>


    </div>
</section>

<section class="footer">
    <div class="container">
        <img class="footer__image" src="main/images/footer.png" alt="">
       <div class="footer__info">
           <div class="footer__block">
               <h3 class="footer__title">Logotype</h3>
               <div class="footer__icons">
                   <img src="main/images/icon1.png" alt="facebook">
                   <img src="main/images/icon2.png" alt="instagram">
                   <img src="main/images/icon3.png" alt="telegram">
                   <img src="main/images/icon4.png" alt="whatsapp">
               </div>
               <p class="footer__descr">Lorem ipsum Lorem ipsum</p>
           </div>

           <div class="footer__contact">
               <h3 class="footer__title">Contact us</h3>
               <p class="footer__description">Phone number: +996 706 05 02 03</p>
               <p class="footer__description">Adress: Ibraimova street 103</p>
               <p class="footer__description3">E-mail: loremipsum@gmail.com</p>
           </div>
       </div>
    </div>
</section>



<script type="text/javascript" src="{% static 'main/js/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/libs/owl-carousel/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>




{% endblock %}


<!--<a class="site" href="{% url 'main:form_view' %}"> Create</a>-->

templates/main/index.html
{% extends 'main/origin.html' %}
{% load static %}


{% block title %}SUAB Bygg och VVS{% endblock %}

{% block content %}
<header class="header">
    <div class="container">
            <div class="header__logo">
                <img src="{{ MEDIA_URL }}/Logo.png" alt="logo">
                <h1 class="header__title"> SUAB Bygg och VVS</h1>
            </div>

        <div class="header__block">
            <h2 class="header__title2"> SUAB Bygg och VVS</h2>
            <p class="header__description">- ett företag som värnar om kunden och dennes intressen. Vårt mål är att alltid ha nöjda kunder,
                <br> nöjda kunder lika vanliga kunder.</p>
                    <a href="{% url 'main:completed' %}">
                        <button class="header__button">Button</button>
                    </a>
        </div>
    </div>
</header>

<section class="main">
    <img class="main__img" src="{{ MEDIA_URL }}/imageMain.png" alt="">
    <div class="container">
            <h2 class="main__title">Om oss</h2>
            <p class="main__description"> SUAB Bygg och VVS — ett företag som värnar om kunden och dennes intressen. Vårt mål är att
                <br> alltid ha nöjda kunder, nöjda kunder lika vanliga kunder.</p>
            <p class="main__description2"> Vi bistår privatpersoner och företag i alla typer av byggentreprenader såsom tillbyggnad, fönsterförsäljning, badrumsrenovering, nybyggnation m.m.</p>

        <div class="main__row">
                <div class="main__block">
                    <div class="main__one">
                        <p class="main__descr">1</p>
                    </div>

                    <div class="main__text">
                        <h3 class="main__title2">TILLBYGGNADER</h3>
                        <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                    </div>
                </div>

               <div class="main__block">
                   <div class="main__one">
                       <p class="main__descr">1</p>
                   </div>

                   <div class="main__text">
                       <h3 class="main__title2">TILLBYGGNADER</h3>
                       <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                   </div>
               </div>

                    <div class="main__block">
                        <div class="main__one">
                            <p class="main__descr">1</p>
                        </div>

                        <div class="main__text">
                            <h3 class="main__title2">TILLBYGGNADER</h3>
                            <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                        </div>
                    </div>


                   <div class="main__block">
                       <div class="main__one">
                           <p class="main__descr">1</p>
                       </div>

                       <div class="main__text">
                           <h3 class="main__title2">TILLBYGGNADER</h3>
                           <p class="main__descr2">Lorem Ipsum is simply dummy text of <br> the printing and typesetting industry.</p>
                       </div>
                   </div>
            </div>
    </div>
</section>

<section class="photo">
            <div class="container">
                            <img class="photo__img" src="{{ MEDIA_URL }}/photo.png" alt="photo">
    //
                <div class="photo__inner">
                    <div class="photo__row">
                        <div class="photo__contents">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo1.png" alt="">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo2.png" alt="">
                        </div>

                        <div class="photo__content">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo5.png" alt="">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo6.png" alt="">
                        </div>

                    </div>

                    <div class="photo__row1">
                        <div class="photo__contents">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo3.png" alt="">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo4.png" alt="">
                        </div>

                        <div class="photo__content">
                            <img class="photo__block" src="{{ MEDIA_URL }}/photo5.png" alt="">
                            <img class="photo__block" src="{{ MEDIA_URL }}/wing.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>

<section class="gallery">
    <div class="container">
        <h2 class="gallery__title">PÅGÅENDE PROJEKT</h2>
        <div class="gallery_inner">
            <div class="gallery__block">
                <a href="{% url 'main:renovation' %}"> <button class="gallery__btn">TOTALRENOVERING ATTEFALLSHUS</button> </a>
                <a href="{% url 'main:projects' %}"> <button class="gallery__btn">TIDIGARE SLUTFÖRDA PROJEKT</button> </a>
            </div>

            <div class="gallery__block">
                <a href="{% url 'main:house_construction' %}"> <button class="gallery__btn">HUSBYGGE - JÄRLÅSA</button> </a>
                <a href="{% url 'main:extensions' %}"> <button class="gallery__btn">TILLBYGGNADER & POOL</button> </a>
            </div>
        </div>


        <div class="owl-carousel owl-theme owl-loaded gallery__carousel">
            <div class="owl-stage-outer">
                <div class="owl-stage">
                    <div class="owl-item gallery__card">
                        <img class="gallery__card-img" src="{{ MEDIA_URL }}/gallery1.png" alt="placeholder">
                    </div>
                    <div class="owl-item team__card">
                        <img class="gallery__card-img" src="{{ MEDIA_URL }}/gallery2.png" alt="placeholder">
                    </div>
                    <div class="owl-item team__card">
                        <img class="gallery__card-img" src="{{ MEDIA_URL }}/gallery3.png" alt="placeholder">
                    </div>
                    <div class="owl-item team__card">
                        <img class="gallery__card-img" src="{{ MEDIA_URL }}/gallery4.png" alt="placeholder">
                    </div>
                    <div class="owl-item team__card">
                        <img class="gallery__card-img" src="{{ MEDIA_URL }}/gallery5.png" alt="placeholder">
                    </div>
                </div>
            </div>
            <div class="owl-dots" id="dots">
                <div class="gallery__dot owl-dot active"><span></span></div>
                <div class="gallery__dot owl-dot"><span></span></div>
                <div class="gallery__dot owl-dot"><span></span></div>
            </div>
        </div>
    </div>
</section>

<section class="fill">
    <div class="container">
        <h2 class="fill__title">VILL DU ATT VI KONTAKTAR DIG? <br>
            FYLL I FORMULÄRET NEDAN SÅ HÖR VI AV OSS TILL DIG</h2>

        <form class="fill__form" action="" method="POST">
            {% csrf_token %}
            {{ form }}

            <div class="fill_btn">
                <button class="fill__btn">SKICKA</button>
            </div>
        </form>
    </div>
</section>


<section class="footer">
    <img class="footer__image" src="{{ MEDIA_URL }}/footer.png" alt="">
    <div class="container">
       <div class="footer__info">
           <div class="footer__block">
               <h3 class="footer__title">Logotype</h3>
               <div class="footer__icons">
                   <img src="{{ MEDIA_URL }}/icon1.png" alt="facebook">
                   <img src="{{ MEDIA_URL }}/icon2.png" alt="instagram">
                   <img src="{{ MEDIA_URL }}/icon3.png" alt="telegram">
                   <img src="{{ MEDIA_URL }}/icon4.png" alt="whatsapp">
               </div>
               <p class="footer__descr">Lorem ipsum Lorem ipsum</p>
           </div>

           <div class="footer__contact">
               <h3 class="footer__title">Contact us</h3>
               <p class="footer__description">Phone number: +996 706 05 02 03</p>
               <p class="footer__description">Adress: Ibraimova street 103</p>
               <p class="footer__description3">E-mail: loremipsum@gmail.com</p>
           </div>
       </div>
    </div>
</section>
{% endblock %}

templates/main/origin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}  {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/libs/owl-carousel/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/libs/owl-carousel/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/fill.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/photo.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/pictures.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/gallery.css' %}">
</head>
<body>

    {% block content %}
    {% endblock %}

        <script type="text/javascript" src="{% static 'main/js/jquery-3.6.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/libs/owl-carousel/owl.carousel.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>
</body>
</html>

templates/main/sampler.html
{% extends 'main/origin.html' %}
{% load static %}

{% block title %}  {% endblock %}

{% block content %}

{% endblock %}


____________________________________________


<a href="{% url 'main:new_page' %}">

</a>

____________________________________________

    <img src="{{ MEDIA_URL }}/icon1.png" alt="">